server {
    listen 8080;
    listen [::]:8080;
    server_name localhost;

    port_in_redirect off;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
